### ISSUE TITLE
Presentaciones

### ISSUE THREAD

**Issue by UlisesGascon** [Fictizia/Curso-JS-para-desarrolladores-web_ed6#1]
Hola!

Usemos este espacio para conocernos un poco más... :-)

Recordad que estos _issues_ nos permiten abrir y participar en debates, compartir recursos, plantear preguntas y muchas cosas más! 

Podemos usar [Markdown](https://guides.github.com/features/mastering-markdown/) para salirnos del texto plano y enriquecer nuestras aportaciones.

**Comment by NuriaHill** [comment]
Nuria. _Bióloga_ y  **gamer** 
Por otro lado espero estar a la altura del curso... :scream:

**Comment by GonzaloOrio** [comment]
Hola soy Gonzalo, vengo del _diseño gráfico y maquetación_, y actualmente intentando evolucionar y desarrollarme en este nuevo mundo para mí.
Como dice Nuria, yo también **espero poder estar a la altura de este curso**
