### ISSUE TITLE
Meetup Open Source Weekends

### ISSUE THREAD

**Issue by UlisesGascon** [Fictizia/Curso-JS-para-desarrolladores-web_ed6#10]
Hola!

[Este](http://www.meetup.com/es-ES/Open-Source-Weekends/) es el grupo de Meetup que os comentaba ayer

**Comment by jgarciaruiz** [comment]
Genial, me acabo de unir @UlisesGascon 👍

**Comment by GonzaloOrio** [comment]
Perfecto Ulises, yo también me acabo de unir. Gracias!

**Comment by NuriaHill** [comment]
Me acabo de unir yo tambien :+1:
