### ISSUE TITLE
permisos para el push

### ISSUE THREAD

**Issue by Inalbis09** [Fictizia/Curso-JS-para-desarrolladores-web_ed6#4]
Estoy realizando el ejercicio a traves de la terminal, cuando termino de hacer todo y quiero hacer el push me da este error en consola, tanto en push como en request-pull:
fatal: unable to access 'https://github.com/Fictizia/Curso-JS-para-desarrolladores-web_ed6.git/': The requested URL returned error: 403

**Comment by UlisesGascon** [comment]
Hola @Inalbis09 !

Acabo de mandar la invitación ;-)

**Comment by Inalbis09** [comment]
Ya está hecho wow!!!!!! Gracias : )
