### ISSUE TITLE
Error con permisos

### ISSUE THREAD

**Issue by vscampo** [Fictizia/Curso-JS-para-desarrolladores-web_ed6#5]
Buenas, yo también estoy teniendo problemas de permisos, el error me da al hacer push

Warning: Permanently added 'github.com,192.30.252.128' (RSA) to the list of known hosts.
ERROR: Permission to Fictizia/Curso-JS-para-desarrolladores-web_ed6.git denied to vscampo.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by UlisesGascon** [comment]
Hola! En principio el problema no es de permisos en el repositorio, si no algún problema entre el cliente gráfico o terminal con GitHub. Si estas usando el cliente gráfico de Windows intenta reinstalar.

**Comment by vscampo** [comment]
Estoy utilizando C9, se atualiza todo bien, pero no me deja subir nada

**Comment by UlisesGascon** [comment]
Que raro.. en la parte de colaboradores si apareces. Intenta lanzar una nueva máquina virtual por si acaso esta la actual no se ha cargado bien del todo...

De todas formas, lo miramos en clase, en un par de horas ;-)

**Comment by vscampo** [comment]
Ok pues ya lo vemos en clase
