### ISSUE TITLE
[Importante] Sobre la seguridad de las cuentas en la red

### ISSUE THREAD

**Issue by UlisesGascon** [Fictizia/Curso-JS-para-desarrolladores-web_ed6#6]
Hola a todos...

Ayer se publicó [esta noticia](http://thehackernews.com/2016/06/github-password-hack.html), desde hace un tiempo mucho portales de redes sociales se han visto comprometidos y se han filtrado usuarios y contraseñas (cifradas y no...). 

Es importante que utilicemos contraseñas diferentes en cada sitio, asi evitamos que nos roben la identidad en otros portales simplemente porque usamos el mismo usuario y contraseña.

Como buena practica adicional, cambiar las contraseñas de todos los servicios cada cierto tiempo.

Os paso un link a [esta web](https://haveibeenpwned.com/). Permite verificar si en algún momento vuestra dirección de email apareció en las listas de alguno de [estos ataques](https://haveibeenpwned.com/PwnedWebsites). Si estáis en la lista y usáis la misma misma combinación de email y contraseña podría ser un riesgo.

A lo largo del curso hablaremos de seguridad en la red, tanto en desarrollo de cliente como personal. 

Buen finde a todos!

**Comment by coma** [comment]
Tomo nota, pero meter mi email en una web para ver si me han hackeado da mal rollo!

**Comment by NuriaHill** [comment]
si, el de gmail anterior y via Tumbrl. el de Hilligehekken parece que esta a salvo.. se ve que a los hackers no le gustan los mails rarunos
