### ISSUE TITLE
return en funciones anidadas

### ISSUE THREAD

**Issue by jgarciaruiz** [Fictizia/Curso-JS-para-desarrolladores-web_ed6#9]
Una duda que me surge, si necesito pasar los return de funciones anidadas a la función primaria, ¿esta forma sería la correcta o habría alguna otra mejor, por ejemplo trabajarlo con una estructura con methods? 

```
function lorem(){
    var qux;
    function subfunctionOne(smth){
        var foo = smth;
        return foo;
    }
    function subfunctionTwo(){
        var bar = 2;
        var yaz = subfunctionOne();
        return yaz * bar;
    }
    var a = subfunctionOne();
    var b = subfunctionTwo(a);

    qux = a+b;
    return qux;
}
```

**Comment by UlisesGascon** [comment]
Hola @jgarciaruiz ! Es una forma válida. Aunque la estructura  del ejemplo es compleja y puede optimizarse mucho, al final _lorem_ retorna la suma de los retornos de _subfunctionOne_ y _subfunctionTwo_.

Otra forma un poco más refinada sería esta:

``` javascript
function lorem(){

    function subfunctionOne(smth){
        return smth || 0; // Para evitar el NaN original
    }
    function subfunctionTwo(){
        return subfunctionOne() * 2;
    }

    var a = subfunctionOne();
    return a + subfunctionTwo(a);
}
```

Aunque lo más común en los retornos suele ser presentar el retorno de las funciones, también podemos exponer las funciones como retorno, de tal forma que podemos crear estructuras mucho más dinámicas que podemos ejecutar con variaciones según cambien las necesidades de nuestro Script, lo que da pie a utilizar patrones de diseño como [Facade](https://www.wikiwand.com/es/Facade_%28patr%C3%B3n_de_dise%C3%B1o%29).

Otro tema que puede ser interesante para reducir la anidación y retornos complejos es utilizar [Closures](https://developer.mozilla.org/es/docs/Web/JavaScript/Closures)

Si quieres en la próxima clase podemos profundizar un poco más en los retornos de funciones y métodos. ;-)

**Comment by jgarciaruiz** [comment]
Entendido, gracias @UlisesGascon !
El patrón de diseño Facade no sé si lo he entendido muy bien, ¿lo que nos permitiría sería escribir código de una forma que permite acceder a los return de las subfunciones desde fuera llamando a la función principal?

Sí, por mi genial profundizar otro poco en retornos y métodos, y si además pudiéramos volver a ver algún ejemplo de Closures para que me quede más claro, perfect :D

**Comment by NuriaHill** [comment]
A mi también me parece un tema interesante a tratar si puedes . Gracias
